window.SITE_CONTENT = {
  brand: {
    name: '이음통합평생교육원',
    siteUrl: 'https://www.ieumedu.kr',
  },
  contact: {
    representative: '선애순',
    businessNumber: '296-05-03812',
    address: '광주광역시 서구 회재로 859, 3층',
    phone: '062-655-4116',
    hours: '평일 09:00 - 18:00',
    email: '',
    facilityReportNumber: '',
    visitNotice: '방문 전 전화 예약 후 내원해 주세요.',
  },
  directorProfile: {
    name: '선애순',
    title: '이음통합평생교육원 원장',
    verificationNotice: '공개 확인 가능한 자료를 기준으로 정리했습니다.',
    referencePages: [
      {
        year: '참고',
        title: '국립중앙도서관 저자 연관 검색',
        type: '저자·서지',
        note: '선애순 저자명 기준 단행본과 학위논문 목록을 확인할 수 있는 기본 서지 페이지',
        sourceLabel: '국립중앙도서관',
        sourceUrl: 'https://www.nl.go.kr/NL/contents/search.do?acConNo=KAC201506623&detailSearch=true&infoTxt=%EC%97%B0%EA%B4%80%EC%A0%80%EC%9E%90%7C%EC%84%A0%EC%95%A0%EC%88%9C',
      },
      {
        year: '참고',
        title: '교보문고 저자 검색',
        type: '저자·서지',
        note: '도서 판매 페이지와 저자 검색 축을 확인할 수 있는 공개 저자 검색 결과',
        sourceLabel: '교보문고',
        sourceUrl: 'https://search.kyobobook.co.kr/search?chrcCode=1116570601&keyword=%EC%84%A0%EC%95%A0%EC%88%9C',
      },
      {
        year: '참고',
        title: 'KBOOKSTORE 저자 페이지',
        type: '저자·서지',
        note: '영유아생활지도 및 상담, 아동독서치료 등 저자 페이지 공개 목록 확인',
        sourceLabel: 'KBOOKSTORE',
        sourceUrl: 'https://kbookstore.com/authors/%EC%84%A0%EC%95%A0%EC%88%9C/',
      },
    ],
    books: [
      {
        year: '2022',
        title: '도형심리 상담 이해와 분석',
        type: '도서',
        note: '고재윤, 선애순, 윤동화 공저',
        sourceLabel: 'Google Books',
        sourceUrl: 'https://books.google.com/books/about/%EB%8F%84%ED%98%95%EC%8B%AC%EB%A6%AC_%EC%83%81%EB%8B%B4_%EC%9D%B4%ED%95%B4%EC%99%80_%EB%B6%84%EC%84%9D.html?id=5mykzwEACAAJ',
      },
      {
        year: '2021',
        title: '영유아생활지도 및 상담',
        type: '도서',
        note: '박순길, 김동례, 선애순 공저',
        sourceLabel: '예스24',
        sourceUrl: 'https://www.yes24.com/product/goods/97519989',
      },
      {
        year: '2020',
        title: '그림을 통한 아동심리 진단 및 해석',
        type: '도서',
        note: '김동례 외 공저',
        sourceLabel: '대한출판문화협회 신간 목록',
        sourceUrl: 'https://member.kpa21.or.kr/wp-content/uploads/sites/2/2020/11/2020%EB%85%84-10%EC%9B%94%EC%9D%98-%EC%8B%A0%EA%B0%84.pdf',
      },
      {
        year: '2018',
        title: '아동문학',
        type: '도서',
        note: '김동례, 권순황, 선애순 공저',
        sourceLabel: '예스24',
        sourceUrl: 'https://www.yes24.com/product/goods/63691110',
      },
      {
        year: '2018',
        title: '영유아발달',
        type: '도서',
        note: '김영애, 선애순, 정효정 공저',
        sourceLabel: '양서원',
        sourceUrl: 'https://www.yswpub.co.kr/book/detail.php?bookSeq=4286&m_category_seq=1&p=2&s_category_seq=38',
      },
      {
        year: '2017',
        title: '아동상담',
        type: '도서',
        note: '박순길, 권순황, 김현진, 선애순, 한재금 공저',
        sourceLabel: '양서원',
        sourceUrl: 'https://www.yswpub.co.kr/book/detail.php?bookSeq=3929',
      },
      {
        year: '2015',
        title: '영아발달',
        type: '도서',
        note: '권순황, 선애순, 이형선 공저',
        sourceLabel: '국립중앙도서관',
        sourceUrl: 'https://www.nl.go.kr/NL/contents/search.do?acConNo=KAC201506623&detailSearch=true&infoTxt=%EC%97%B0%EA%B4%80%EC%A0%80%EC%9E%90%7C%EC%84%A0%EC%95%A0%EC%88%9C',
      },
      {
        year: '2010',
        title: '아동 독서치료 : 이론과 실제',
        type: '도서',
        note: '선애순 저',
        sourceLabel: '예스24',
        sourceUrl: 'https://www.yes24.com/product/goods/4179186',
      },
    ],
    papers: [
      {
        year: '2012',
        title: '다문화가정 아동의 가족기능과 사회적 능력과의 관계',
        type: '학술지',
        note: '선애순, 이미나 공저 / 심리행동연구 4(1)',
      },
      {
        year: '2011',
        title: '다문화가정 수줍음 아동의 독서치료 프로그램 효과',
        type: '학술지',
        note: '이미나, 선애순 공저 / 독서치료연구 4(1)',
        sourceLabel: 'RISS',
        sourceUrl: 'https://m.riss.kr/search/detail/DetailView.do?control_no=3c7952fe555d547cb7998d826d417196&p_mat_type=1a0202e37d52c72d',
      },
      {
        year: '2010',
        title: '그림동화책 읽어주기가 다문화가정 아동의 언어능력 향상에 미치는 효과',
        type: '학술지',
        note: '선애순, 권순황 공저 / 특수아동교육연구 12(2)',
        sourceLabel: 'KCI',
        sourceUrl: 'https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001451625',
      },
      {
        year: '2010',
        title: '이혼가정 아동의 정서적 행동 변화를 위한 모래상자치료 사례연구',
        type: '학술지',
        note: '모래상자치료연구 1(1)',
        sourceLabel: 'RISS',
        sourceUrl: 'https://m.riss.kr/search/detail/DetailView.do?control_no=5d8d4f9f610bde2247de9c1710b0298d&p_mat_type=1a0202e37d52c72d',
      },
    ],
    theses: [
      {
        year: '2013',
        title: '아동의 모래상자치료에서 상징물, 관계성, 심리적 표현 및 개성화 과정에 관한 연구',
        type: '박사학위논문',
        note: '목포대학교 대학원',
        sourceLabel: 'DBpia',
        sourceUrl: 'https://www.dbpia.co.kr/journal/detail?nodeId=T13228110',
      },
      {
        year: '2010',
        title: '그림동화책 읽어주기가 다문화가정 아동의 언어능력 향상에 미치는 효과',
        type: '석사학위논문',
        note: '광신대학교 교육대학원 유아특수교육',
        sourceLabel: '국회도서관',
        sourceUrl: 'https://dl.nanet.go.kr/SearchDetailView.do?cn=KDMT1201031018',
      },
    ],
    publicEducation: [
      {
        year: '2022',
        title: '고창교육지원청 위(Wee)센터 교원연수 실시',
        type: '공공기관 연수',
        note: '주제: 학생 위기상담 개입과 실제 / 강사: 샘아동심리연구원 선애순',
        sourceLabel: '고창교육지원청',
        sourceUrl: 'https://school.jbedu.kr/gce/MABBFAEAB/view/5354920?s_idx=1',
      },
      {
        year: '2020',
        title: '돌봄전담사 역량강화 연수 실시',
        type: '공공기관 연수',
        note: '주제: 아동발달 과정 이해를 통한 돌봄 / 고창교육지원청 공개 게시물',
        sourceLabel: '고창교육지원청',
        sourceUrl: 'https://school.jbedu.kr/gce/MABBDAFAC/view/4495163.do',
      },
      {
        year: '2019',
        title: '(군립도서관) 부모교육/아빠와 함께 책 놀이터 프로그램',
        type: '부모교육',
        note: '영광군립도서관 연계 공개 카페 공지에서 선애순 강사 정보가 확인된 부모교육 프로그램',
        sourceLabel: '네이버 카페',
        sourceUrl: 'https://cafe.naver.com/misopiaa1004/24364',
      },
    ],
    news: [
      {
        year: '2024',
        title: '광주100인의 아빠단 멘토링 체험 성료',
        type: '뉴스',
        note: '샘아동심리연구원 선애순 원장이 아빠단 멘토링 체험 프로그램을 진행한 기사',
        sourceLabel: '베이비뉴스',
        sourceUrl: 'https://www.ibabynews.com/news/articleView.html?idxno=120744',
      },
      {
        year: '2010',
        title: '완도군 건강가정지원센터장으로 가족 방문상담 활동 소개',
        type: '뉴스',
        note: '여성신문 기사에서 선애순 센터장의 가족상담 현장 활동이 소개됨',
        sourceLabel: '여성신문',
        sourceUrl: 'https://www.womennews.co.kr/news/articleView.html?idxno=47287',
      },
    ],
  },
  externalLinks: [
    { label: '이음교육저널', url: 'https://news.ieumedu.kr/' },
    { label: '블로그', url: 'https://think-sis.co.kr' },
    { label: '브런치북', url: 'https://brunch.co.kr/@205593d149c84b6' },
    { label: '민간자격정보서비스', url: 'https://www.pqi.or.kr' },
  ],
  home: {
    heroBadge: '평생교육원 · 민간자격 · 심리상담',
    heroTitleLines: ['마음을 잇는 교육,', '성장을 잇는 상담'],
    heroDescLines: [
      '이음통합평생교육원은 모래놀이심리상담사 양성을 통해',
      '아동·청소년·성인의 심리적 성장을 지원합니다.',
    ],
    introTitle: '이음통합평생교육원',
    introDesc: '모래놀이심리상담 전문 교육기관으로서 체계적인 이론 교육과 실습을 통해 전문 상담 인력을 양성합니다.',
    infoStrip: [
      { icon: '📍', label: '주소', value: '광주광역시 서구 회재로 859, 3층' },
      { icon: '☎', label: '전화', value: '062-655-4116' },
      { icon: '🕐', label: '운영', value: '평일 09:00 - 18:00' },
      { icon: '🌐', label: '웹사이트', value: 'https://www.ieumedu.kr' },
    ],
    missionCards: [
      { title: '체계적 교육과정', desc: '발달심리, 상담이론, 모래놀이치료 등 단계별 커리큘럼을 운영합니다.', icon: '📚' },
      { title: '민간자격 발급', desc: '모래놀이심리상담사 2급·1급 자격 과정을 통해 전문성을 인증합니다.', icon: '🏅' },
      { title: '전문 상담 연계', desc: '이음심리연구상담센터와 연계하여 실질적인 상담 경험을 제공합니다.', icon: '🤝' },
    ],
    previewCourses: [
      { level: '2급', title: '모래놀이심리상담사 2급', hours: '이론 40시간 + 실습', desc: '심리상담 기초 이론, 발달심리, 모래놀이치료 입문', tag: '모집중' },
      { level: '1급', title: '모래놀이심리상담사 1급', hours: '이론 60시간 + 실습', desc: '심층 상담이론, 사례분석, 모래놀이 치료기법 심화', tag: '준비중' },
      { level: 'Pro', title: '전문가 과정', hours: '추후 안내', desc: '수료자 대상 전문가 과정 (세부 일정 추후 공지)', tag: '예정' },
    ],
    scheduleHighlights: [
      {
        label: '교육일정',
        title: '2급 과정 상담 접수 중',
        detail: '상담 접수 후 개강 일정 개별 안내',
      },
      {
        label: '자격시험',
        title: '과정별 검정 일정 별도 공지',
        detail: '교육 종료 후 검정 일정과 합격자 발표 안내',
      },
      {
        label: '전문가 과정',
        title: '세부 일정 준비 중',
        detail: '1급 수료자 대상 심화 과정은 추후 공지',
      },
    ],
    ctaTitle: '교육 상담 및 수강신청',
    ctaDesc: '궁금한 점이 있으시면 언제든 문의해 주세요.',
  },
  courses: {
    curriculum2: [
      '아동발달심리 개론',
      '상담심리학 기초',
      '이상심리 및 정신병리',
      '모래놀이치료 이론',
      '모래놀이 상징 해석',
      '사례 연구 및 분석',
      '상담 윤리와 법규',
      '실습 및 수퍼비전',
    ],
    curriculum1: [
      '심층 발달심리학',
      '정신분석 상담이론',
      '대상관계이론',
      '융 분석심리학',
      '모래놀이치료 심화기법',
      '투사검사 해석',
      '사례 발표 및 토론',
      '슈퍼비전 실습',
    ],
  },
  schedule: {
    items: [
      {
        id: 'course-2',
        title: '모래놀이심리상담사 2급',
        status: '상담 접수 중',
        format: '대면 중심',
        audience: '입문자 · 일반 수강 가능',
        application: '상시 상담 접수',
        classSchedule: '개강 일정 개별 안내',
        examSchedule: '교육 종료 후 자격검정 일정 공지',
        desc: '기초 과정은 모집 수요를 기준으로 개설 일정을 확정하며, 상담 접수자에게 교육 일정과 검정 일정을 순차 안내합니다.',
      },
      {
        id: 'course-1',
        title: '모래놀이심리상담사 1급',
        status: '준비 중',
        format: '심화 과정',
        audience: '2급 취득자 대상',
        application: '대상자 별도 안내',
        classSchedule: '개설 시 공지사항 안내',
        examSchedule: '과정 운영 후 별도 검정 일정 안내',
        desc: '1급 과정은 2급 자격 취득자를 대상으로 운영하며, 모집 공지와 자격검정 일정은 공지사항에서 별도 안내합니다.',
      },
      {
        id: 'course-pro',
        title: '전문가 과정',
        status: '추후 공지',
        format: '수퍼비전 중심',
        audience: '1급 수료자 대상 예정',
        application: '추후 공지',
        classSchedule: '운영안 확정 후 안내',
        examSchedule: '해당 없음 / 심화과정 별도 기준 적용',
        desc: '심화 수퍼비전 및 전문가 과정을 단계적으로 개설할 예정이며, 세부 일정은 운영안 확정 후 공지합니다.',
      },
    ],
    examTimeline: [
      ['상담 · 접수', '홈페이지 또는 전화 상담으로 수강 의사 접수'],
      ['교육 일정 안내', '과정별 개강일, 교육시간, 준비물 개별 안내'],
      ['자격검정 공지', '교육 종료 후 자격시험 일정과 응시 절차 공지'],
      ['합격자 안내', '검정 후 합격 여부 및 자격증 발급 절차 안내'],
    ],
    notice: '개강일, 모집 인원, 교육 방식, 준비물, 자격검정 일정은 공지사항과 교육일정 페이지에서 함께 안내하며, 접수자에게는 개별 연락으로도 안내합니다.',
  },
  refund: {
    rows: [
      ['수업 시작 전', '납부한 학습비 전액 반환'],
      ['총수업시간의 1/3 이전', '납부한 학습비의 2/3 해당액 반환'],
      ['총수업시간의 1/3 경과 ~ 1/2 이전', '납부한 학습비의 1/2 해당액 반환'],
      ['총수업시간의 1/2 경과 후', '반환하지 않음'],
    ],
    requestGuide: '학습비 반환은 수강 취소 의사 확인 후 처리합니다. 개강 여부, 실제 수업 진행 시간, 과정 운영 형태에 따라 세부 계산이 달라질 수 있으므로, 반환 요청 전 행정 안내를 먼저 받아 주세요.',
    notes: [
      '교재비, 재료비, 자격발급 관련 비용은 별도일 수 있습니다.',
      '모집 인원 미달로 폐강되는 경우 학습비는 전액 반환합니다.',
      '세부 반환 운영은 최종 개설 공지와 접수 안내 기준을 따릅니다.',
    ],
  },
  enroll: {
    gasUrl: 'https://script.google.com/macros/s/AKfycbwf5igmKxMVPSSuyxAxwRRcwU0xlV1Gf7EzlBpBtWn1maSQ1VCWFRyPphOFotVZde4z/exec',
    turnstileSiteKey: '',
    turnstileAction: 'enroll_form',
    turnstileRequired: false,
    successTitle: '신청이 접수되었습니다',
    successDesc: '담당자가 확인 후 연락드리겠습니다.',
    fallbackTitle: '신청 내용은 작성되었지만 자동 접수는 완료되지 않았습니다',
    fallbackDesc: '아래 버튼으로 신청 내용을 복사하거나 문자·이메일로 전달해 주세요.',
    links: [
      { label: '블로그 (think-sis.co.kr)', url: 'https://think-sis.co.kr' },
      { label: '브런치북 『감정도 잠이 필요하다』', url: 'https://brunch.co.kr/@205593d149c84b6' },
    ],
  },
  faq: [
    {
      q: '수강신청은 어떻게 진행되나요?',
      a: '홈페이지 또는 상담 접수를 통해 신청 의사를 남기면 과정별 운영 일정에 맞춰 접수와 안내를 진행합니다. 과정에 따라 선착순 또는 상담 후 등록 방식으로 운영될 수 있습니다.',
    },
    {
      q: '개강 전 별도 안내가 있나요?',
      a: '개강 일정, 운영 방식, 준비물, 강의실 등의 세부 내용은 공지사항 또는 개별 연락을 통해 안내합니다.',
    },
    {
      q: '수강료와 재료비는 모두 포함인가요?',
      a: '기본 학습비와 별도 비용 항목은 과정별로 다를 수 있습니다. 자격검정료, 발급비, 교재비, 재료비는 별도 안내될 수 있습니다.',
    },
    {
      q: '학습비 반환은 어떻게 되나요?',
      a: '학습비 반환은 평생교육법 시행령 기준에 따라 처리합니다. 상세 기준은 학습비 반환 안내 페이지를 참고해 주세요.',
    },
    {
      q: '민간자격 과정은 누구나 신청 가능한가요?',
      a: '2급 과정은 일반 수강이 가능하도록 운영하고, 1급 이상 심화 과정은 선행 자격 또는 수료 조건이 있을 수 있습니다.',
    },
  ],
  notices: [
    {
      id: 'notice-001',
      date: '2026-04-20',
      pinned: true,
      title: '모래놀이심리상담사 2급 과정 상담 접수 안내',
      category: '수강안내',
      body: '2급 과정은 현재 상담 접수를 우선 진행하고 있으며, 개강 일정은 문의 순서와 모집 현황에 따라 안내합니다.',
    },
    {
      id: 'notice-002',
      date: '2026-04-18',
      pinned: false,
      title: '1급 과정은 2급 자격 취득자 대상 별도 안내',
      category: '자격과정',
      body: '1급 과정은 2급 자격 취득자를 대상으로 운영되며, 개설 시 공지사항을 통해 상세 요건과 일정을 안내합니다.',
    },
    {
      id: 'notice-003',
      date: '2026-04-15',
      pinned: false,
      title: '전문가 과정 세부 운영안 추후 공지',
      category: '예정',
      body: '전문가 과정은 단계별로 준비 중이며, 수퍼비전 및 심화 실습 중심으로 구성할 예정입니다.',
    },
  ],
  institution: {
    infoRows: [
      ['기관명', '이음통합평생교육원'],
      ['대표자', '선애순'],
      ['사업자등록번호', '296-05-03812'],
      ['소재지', '광주광역시 서구 회재로 859, 3층'],
      ['발행소 주소', '광주광역시 서구 회재로 859, 3층 이음통합평생교육원'],
      ['대표전화', '062-655-4116'],
      ['운영시간', '평일 09:00 - 18:00'],
      ['홈페이지', 'https://www.ieumedu.kr'],
    ],
    operationRows: [
      ['주요 안내', '모래놀이심리상담사 2급·1급 과정 소개, 수강상담, 교육일정, 민간자격 관련 정보를 제공합니다.'],
      ['상담 접수', '홈페이지 수강신청 또는 전화 문의를 통해 상담을 접수할 수 있습니다.'],
      ['방문 상담', '방문 상담은 사전 예약 후 진행합니다.'],
    ],
    adminNotice: '개강 일정, 모집 현황, 학습비 반환 기준, 자격 운영 안내는 공지사항과 수강안내 페이지에서 최신 내용을 확인해 주세요.',
    notes: [
      '민간자격 관련 세부 내용은 별도 자격 안내 페이지에서 확인할 수 있습니다.',
      '교육 일정과 개강 여부는 모집 현황에 따라 공지사항 및 개별 안내로 안내합니다.',
      '문의 접수 후 담당자가 순차적으로 연락드립니다.',
    ],
  },
  location: {
    directionsUrl: 'https://www.google.com/maps/search/?api=1&query=%EA%B4%91%EC%A3%BC%EA%B4%91%EC%97%AD%EC%8B%9C+%EC%84%9C%EA%B5%AC+%ED%9A%8C%EC%9E%AC%EB%A1%9C+859+3%EC%B8%B5+%EC%9D%B4%EC%9D%8C%ED%86%B5%ED%95%A9%ED%8F%89%EC%83%9D%EA%B5%90%EC%9C%A1%EC%9B%90',
    directionsLabel: '길찾기 열기',
    mapImage: 'uploads/location/location-map.jpeg',
    mapImageAlt: '이음심리연구상담센터 및 이음통합평생교육원 약도',
    qrImage: 'uploads/location/location-directions-qr.png',
    qrAlt: '이음통합평생교육원 길찾기 QR 코드',
    mapNotice: '방문 전 전화 예약 후 내원해 주세요. QR 코드를 촬영하면 교육원 위치 검색 페이지가 열립니다.',
    transit: [
      '광주 서부 송신물공판장 인근, 제2순환도로와 서부농수산물시장 인접 지역입니다.',
      '풍암119안전센터, 운리초·운리중·풍암고 방향에서 접근이 가능합니다.',
      '주소 검색은 "광주광역시 서구 회재로 859, 3층" 또는 "이음통합평생교육원" 기준으로 이용해 주세요.',
    ],
  },
  certification: {
    statusNotice: '민간자격 운영 정보와 세부 고시는 자격 안내 페이지와 공지사항을 통해 안내합니다. 동일 명칭의 자격과 혼동되지 않도록 등록번호 확인 전에는 임의 표기를 하지 않습니다.',
    infoRows: [
      ['자격명', '모래놀이심리상담사 2급 / 1급'],
      ['자격관리 운영기관', '이음심리연구상담센터 · 대한심리통합연구회'],
      ['교육기관', '이음통합평생교육원'],
      ['자격 유형', '민간자격(등록 진행 기준 안내)'],
      ['등록번호', ''],
    ],
    consumerNotice: [
      '상기 자격은 자격기본법 규정에 따른 민간자격 운영 기준으로 안내하며, 국가공인 자격이 아닙니다.',
      '민간자격 등록 및 공인 제도에 관한 상세 사항은 민간자격정보서비스(PQI)에서 확인할 수 있습니다.',
      '교육과정 운영기관과 자격관리·발급기관의 역할은 운영 구조에 따라 구분하여 안내합니다.',
      '총비용, 응시료, 환불규정 등 운영 세부 사항은 자격 안내 페이지와 공지사항 기준으로 안내합니다.',
    ],
    operationRules: {
      title: '모래놀이심리상담사 민간자격 운영 총칙',
      effectiveDate: '2026년 5월 1일',
      summary: [
        '자격명은 모래놀이심리상담사이며 2급과 1급으로 구분합니다.',
        '2급은 상담 보조·관찰·사례기록 중심의 기초 역량, 1급은 심화 상담 설계·사례분석·위기대응 중심의 고급 역량을 다룹니다.',
        '교육, 검정, 자격증 발급 및 운영의 기본 체계와 문서·기록 관리 원칙을 규정합니다.',
        '규정 개정과 시행 공지는 검정위원회 심의 및 공식 공지 절차를 따르도록 되어 있습니다.',
      ],
      downloadLabel: '운영총칙 원문 다운로드',
      downloadUrl: 'uploads/docs/private-certification-regulations.hwpx',
    },
    verifyPolicy: [
      '자격인증 조회 결과는 교육원 또는 자격관리기관이 보관하는 발급 기록을 기준으로 안내합니다.',
      '조회 정보는 합격자 명부와 자격 발급대장을 바탕으로 확인합니다.',
      '정확한 확인을 위해 자격번호, 성명, 발급일, 등급, 발급기관 정보를 기준 기록과 대조합니다.',
    ],
  },
  verify: {
    records: [
      {
        certNo: '2026-02-2-0001',
        name: '예시수강생A',
        birth: '2000.**.**',
        level: '모래놀이심리상담사 2급',
        issueDate: '2026년 2월 23일',
        issuer: '대한심리통합연구회',
        valid: true,
      },
      {
        certNo: '2026-03-1-0002',
        name: '예시수강생B',
        birth: '1998.**.**',
        level: '모래놀이심리상담사 1급',
        issueDate: '2026년 3월 14일',
        issuer: '대한심리통합연구회',
        valid: true,
      },
    ],
  },
  footer: {
    partnerOrganizations: ['이음심리연구상담센터', '대한심리통합연구회'],
  },
};
